In [4]:
!nvidia-smi

Thu Oct 26 18:03:41 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   58C    P8    10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [5]:
!pip -q install transformers peft accelerate bitsandbytes getpass4 torchrl sentencepiece

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [7]:
import pickle
with open("/content/drive/MyDrive/robotics+llm/Data/image_embeddings.pickle", "rb") as f:
  data = pickle.load(f)

In [8]:
import torch

img_embeddings = []
next_img_embeddings = []
actions = []
instructions = []
for key in data:
  item = data[key]
  img_embeddings.append(item[0])
  next_img_embeddings.append(item[2])
  actions.append(torch.tensor(item[1]).reshape(-1, 2))
  instructions.append(item[3])

img_embeddings_t= torch.cat(img_embeddings, dim=0)
next_img_embeddings_t = torch.cat(next_img_embeddings, dim=0)
actions_t = torch.cat(actions, dim=0)

In [9]:
img_embeddings_t.shape, next_img_embeddings_t.shape, actions_t.shape, len(instructions)

(torch.Size([252, 768]), torch.Size([252, 768]), torch.Size([252, 2]), 252)

In [10]:
from getpass import getpass
hf_token = getpass("Huggingface access token")

Huggingface access token··········


In [11]:
import bitsandbytes as bnb
import os
import torch

from transformers import LlamaForCausalLM, LlamaTokenizer, BitsAndBytesConfig

device_map = "auto"

base_model = "meta-llama/Llama-2-7b-chat-hf"
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16
)

model = LlamaForCausalLM.from_pretrained(
    base_model,
    quantization_config=bnb_config,
    device_map=device_map,
    token=hf_token
)



Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py:374: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(


In [12]:
tokenizer = LlamaTokenizer.from_pretrained(base_model, token=hf_token)
tokenizer.add_special_tokens(
    {
        "pad_token": "<PAD>",
    }
)
model.config.pad_token_id = tokenizer.pad_token_id
special_tokens_dict = {'additional_special_tokens': ['<IMG>', '<X>', '<Y>']}
num_added_toks = tokenizer.add_special_tokens(special_tokens_dict)
model.resize_token_embeddings(len(tokenizer))

Embedding(32004, 4096)

In [13]:
tokenizer.get_added_vocab()

{'<unk>': 0,
 '<s>': 1,
 '</s>': 2,
 '<PAD>': 32000,
 '<Y>': 32001,
 '<X>': 32002,
 '<IMG>': 32003}

In [14]:
model

LlamaForCausalLM(
  (model): LlamaModel(
    (embed_tokens): Embedding(32004, 4096)
    (layers): ModuleList(
      (0-31): 32 x LlamaDecoderLayer(
        (self_attn): LlamaAttention(
          (q_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (k_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (v_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (o_proj): Linear4bit(in_features=4096, out_features=4096, bias=False)
          (rotary_emb): LlamaRotaryEmbedding()
        )
        (mlp): LlamaMLP(
          (gate_proj): Linear4bit(in_features=4096, out_features=11008, bias=False)
          (up_proj): Linear4bit(in_features=4096, out_features=11008, bias=False)
          (down_proj): Linear4bit(in_features=11008, out_features=4096, bias=False)
          (act_fn): SiLUActivation()
        )
        (input_layernorm): LlamaRMSNorm()
        (post_attention_layernorm): LlamaRMSNorm()
      )
    )
    (norm

In [15]:
from peft import (
    LoraConfig,
    get_peft_model,
    get_peft_model_state_dict,
    prepare_model_for_int8_training,
    prepare_model_for_kbit_training,
    set_peft_model_state_dict,
    get_peft_config,
    PromptTuningInit,
    PromptTuningConfig,
    TaskType,
    PeftType
)

lora_r = 16
lora_alpha = 32
lora_dropout = 0.1
lora_target_modules = ".*(q_proj|k_proj|v_proj|o_proj|gate_proj|down_proj|up_proj|lm_head)$"
model = prepare_model_for_kbit_training(model)
peft_config = LoraConfig(
    r=lora_r,
    lora_alpha=lora_alpha,
    target_modules=lora_target_modules,
    lora_dropout=lora_dropout,
    bias="none",
    task_type="CAUSAL_LM"
)
model = get_peft_model(model, peft_config)
model.print_trainable_parameters()

trainable params: 40,554,560 || all params: 6,779,002,944 || trainable%: 0.5982378284094754


In [16]:
model

PeftModelForCausalLM(
  (base_model): LoraModel(
    (model): LlamaForCausalLM(
      (model): LlamaModel(
        (embed_tokens): Embedding(32004, 4096)
        (layers): ModuleList(
          (0-31): 32 x LlamaDecoderLayer(
            (self_attn): LlamaAttention(
              (q_proj): Linear4bit(
                in_features=4096, out_features=4096, bias=False
                (lora_dropout): ModuleDict(
                  (default): Dropout(p=0.1, inplace=False)
                )
                (lora_A): ModuleDict(
                  (default): Linear(in_features=4096, out_features=16, bias=False)
                )
                (lora_B): ModuleDict(
                  (default): Linear(in_features=16, out_features=4096, bias=False)
                )
                (lora_embedding_A): ParameterDict()
                (lora_embedding_B): ParameterDict()
              )
              (k_proj): Linear4bit(
                in_features=4096, out_features=4096, bias=False
              

In [17]:
# Labels
import torchrl

class ActionTokenizer:
  def __init__(self,
               action_spec: dict,
               vocab_size: int,
               action_order=None):
    self.action_spec = action_spec
    self.vocab_size = vocab_size
    if action_order is None:
      self.action_order = self.action_spec.keys()
    else:
      for action in action_order:
        if action not in self.action_spec.keys():
          raise ValueError(f"actions: {action} not found in action_spec: {action_spec.keys()}")
        assert action in self.action_spec.keys()
      self.action_order = action_order

  def tokenize(self, actions):
    """Tokenizes an action."""
    action_tokens = []
    for k in self.action_order:
      a = actions[k]  # a is [batch, actions_size]
      spec = self.action_spec[k]
      a = torch.clip(a, spec.space.low, spec.space.high)
      # Normalize the action [batch, actions_size]
      token = (a - spec.space.low) / (spec.space.high - spec.space.low)
      # Bucket and discretize the action to vocab_size, [batch, actions_size]
      token = (token * (self.vocab_size -1))
      token = token.type(torch.int32)
      action_tokens.append(token)
    # Append all actions, [batch, all_actions_size]
    action_tokens = torch.cat(action_tokens, axis=-1)
    return action_tokens

  def detokenize(self, action_tokens):
    """Detokenizes an action."""
    action = {}
    token_index = 0
    for k in self.action_order:
      spec = self.action_spec[k]
      action_dim = spec.shape[0]
      actions = []
      for _ in range(action_dim):
        spec_index = token_index % action_dim
        a = action_tokens[..., token_index:token_index + 1]
        a = a.type(torch.float32)
        a = a / (self.vocab_size - 1)
        a = (a * (spec.space.high[spec_index] - spec.space.low[spec_index])) + spec.space.low[spec_index]
        actions.append(a)
        token_index += 1
      action[k] = torch.cat(actions, axis=-1)
    return action


/usr/local/lib/python3.10/dist-packages/torchrl/__init__.py:32: UserWarning: failed to set start method to spawn, and current start method for mp is fork.
  warn(


In [18]:
# action_spec = {
#     "dX": torchrl.data.BoundedTensorSpec(low=-10., high=10., shape=(1,), dtype=torch.float32),
#     "dY": torchrl.data.BoundedTensorSpec(low=-10., high=10., shape=(1,), dtype=torch.float32)
# }
# vocab_size = 1000000
# action_tokenizer = ActionTokenizer(action_spec, vocab_size)

In [19]:
# action = { "dX": torch.Tensor([-0.1]), "dY": torch.Tensor([1.2]) }
# toks = action_tokenizer.tokenize(action)
# toks

In [20]:
# action_tokenizer.detokenize(toks)

In [146]:
from torch.utils.data import Dataset

class LlameDataset(Dataset):
  def __init__(self,
               img_embeddings,
               next_image_embeddings,
               actions,
               instructions,
               tokenizer):
    self.img_embeddings = img_embeddings
    self.next_image_embeddings = next_image_embeddings
    self.actions = actions
    self.instructions = instructions
    self.tokenizer = tokenizer

  def __len__(self):
    return self.img_embeddings.shape[0]

  def __getitem__(self, idx):
    img_emb = self.img_embeddings[idx]
    next_img_emb = self.next_image_embeddings[idx]
    act = self.actions[idx]
    inst = self.instructions[idx]
    ins_prefix = "<s>Given "
    ins_suffix = f", {inst} <X> <Y></s>"
    ins_prefix_tokens = self.tokenizer(ins_prefix, return_tensors="pt", add_special_tokens=False)
    ins_suffix_tokens = self.tokenizer(ins_suffix, return_tensors="pt", padding=False, max_length=100, add_special_tokens=False)
    ins_placeholder = f"{ins_prefix}<IMG>{ins_suffix}"
    ins_tokens = self.tokenizer(ins_placeholder, return_tensors="pt", add_special_tokens=False, padding=False, max_length=105)

    return {
        "current_img_emb": img_emb,
        "next_img_emb": next_img_emb,
        "ins_prefix_tokens": ins_prefix_tokens,
        "ins_suffix_tokens": ins_suffix_tokens,
        "ins_placeholder_tokens": ins_tokens,
        "action_x": act[0],
        "action_y": act[1]
    }

In [147]:
ds = LlameDataset(
    img_embeddings_t[:10],
    next_img_embeddings_t[:10],
    actions_t[:10],
    instructions[:10],
    tokenizer
)

In [148]:
len(ds)

10

In [149]:
import torch.nn as nn
vit_to_llm = nn.Linear(768, 4096).to("cuda")

X_head = nn.Sequential(
    nn.Linear(4096, 256),
    nn.ReLU(),
    nn.Dropout(),
    nn.Linear(256, 1)
).to("cuda")
Y_head = nn.Sequential(
    nn.Linear(4096, 256),
    nn.ReLU(),
    nn.Dropout(),
    nn.Linear(256, 1)
).to("cuda")
next_img_head = nn.Sequential(
    nn.Linear(4096, 1024),
    nn.ReLU(),
    nn.Dropout(),
    nn.Linear(1024, 1024),
    nn.ReLU(),
    nn.Dropout(),
    nn.Linear(1024, 768)
).to("cuda")

In [150]:
# dx = act_tokens[0].item()
# dy = act_tokens[1].item()
# ins_prefix = "<s>Given "
# ins_suffix = f", move the red block to the green block. Actions: <X>|<Y></s>"
# ins_prefix_tokens = tokenizer(ins_prefix, return_tensors="pt", add_special_tokens=False)
# ins_suffix_tokens = tokenizer(ins_suffix, return_tensors="pt", add_special_tokens=False, padding="max_length", max_length=100)

In [151]:
# ins_suffix

In [152]:
# ins_placeholder = f"{ins_prefix}<IMG>{ins_suffix}"
# ins_tokens = tokenizer(ins_placeholder, return_tensors="pt", add_special_tokens=False, padding="max_length", max_length=105)
# ins_tokens["input_ids"].shape

In [153]:
# ins_prefix_tokens

In [154]:
# ins_suffix_tokens["input_ids"].shape

In [155]:
# ins_prefix_embeddings = model.model.embed_tokens(ins_prefix_tokens["input_ids"])
# ins_suffix_embeddings = model.model.embed_tokens(ins_suffix_tokens["input_ids"])

In [156]:
# img_embeddings = vit_to_llm(_x[0].unsqueeze(0).to("cuda")).to("cuda")
# img_embeddings.shape

In [157]:
# ins_prefix_embeddings.shape

In [158]:
# ins_suffix_embeddings.shape

In [159]:
# embeddings = torch.cat([ins_prefix_embeddings, img_embeddings, ins_suffix_embeddings], dim=1)
# embeddings.shape

In [160]:
# labels = ins_tokens["input_ids"]
# labels

In [161]:
# labels.shape

In [162]:
from torch.utils.data import DataLoader

train_dataloader = DataLoader(
    ds,
    batch_size=1,
    shuffle=True,
    num_workers=1
)


In [163]:
import gc

In [164]:
from tqdm.auto import tqdm
from torch.optim import AdamW
import time
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, clear_output
import torch.nn.functional as F
import random
from torch.autograd import Variable
from itertools import chain

lr = 1e-3

mse_loss = torch.nn.MSELoss()

trainable_models = chain(
    model.parameters(),
    vit_to_llm.parameters(),
    X_head.parameters(),
    Y_head.parameters(),
    next_img_head.parameters()
)

optimizer = AdamW(params=trainable_models, lr=lr)

losses_total = []
losses_vit = []
losses_x = []
losses_y = []
losses_next = []
losses_ce = []

grads_total = []
grads_vit = []
grads_x = []
grads_y = []
grads_next = []

num_epochs = 56
for epoch in tqdm(range(num_epochs)):
  gc.collect()
  for i, batch in tqdm(enumerate(train_dataloader)):
      mapped_img_embeddings = vit_to_llm(batch["current_img_emb"].reshape(batch["current_img_emb"].shape[0], 1, -1).to("cuda"))
      ins_prefix_embeddings = model.base_model.model.model.embed_tokens(batch["ins_prefix_tokens"]["input_ids"].squeeze(1))
      ins_suffix_embeddings = model.base_model.model.model.embed_tokens(batch["ins_suffix_tokens"]["input_ids"].squeeze(1))
      embeddings = torch.cat([ins_prefix_embeddings, mapped_img_embeddings, ins_suffix_embeddings], dim=1)

      out = model(inputs_embeds=embeddings.half(), labels=batch["ins_placeholder_tokens"]["input_ids"], output_hidden_states=True)

      last_hidden_state = out.hidden_states[-1][:, -1, :].type(torch.float32)
      x_out = X_head(last_hidden_state)
      y_out = Y_head(last_hidden_state)
      next_img_out = next_img_head(last_hidden_state)

      ce_loss = out.loss
      x_loss = mse_loss(batch["action_x"].to("cuda"), x_out)
      y_loss = mse_loss(batch["action_y"].to("cuda"), y_out)
      next_img_loss = mse_loss(batch["next_img_emb"].to("cuda"), next_img_out)

      loss =  ce_loss + x_loss + y_loss + next_img_loss

      # loss.backward(retain_graph=True)

      # if step % 100 == 0:
      #     G_loss = torch.autograd.grad(loss, W.parameters(), retain_graph=True, create_graph=True)
      #     G_loss_norm = torch.norm(G_loss[0], 2) # G_loss[0] = weights G_loss[1] = bias
      #     G_triplet = torch.autograd.grad(loss_triplet, W.parameters(), retain_graph=True, create_graph=True)
      #     G_triplet_norm = torch.norm(G_triplet[0], 2)
      #     G_ce = torch.autograd.grad(loss_ce, W.parameters(), retain_graph=True, create_graph=True)
      #     G_ce_norm = torch.norm(G_ce[0], 2)

      #     grads_total.append(G_loss_norm.item())
      #     grads_triplets.append(G_triplet_norm.item())
      #     grads_ce.append(G_ce_norm.item())

      loss.backward()
      optimizer.step()
      optimizer.zero_grad()

      # if step % 100 == 0:
      losses_total.append(loss.item())
      losses_ce.append(ce_loss.item())
      losses_x.append(x_loss.item())
      losses_y.append(y_loss.item())
      losses_next.append(next_img_loss.item())

  avg_total_loss = sum(losses_total) / ((epoch + 1) * len(train_dataloader))
  avg_ce_loss = sum(losses_ce) / ((epoch + 1) * len(train_dataloader))
  avg_x_loss = sum(losses_x) / ((epoch + 1) * len(train_dataloader))
  avg_y_loss = sum(losses_y) / ((epoch + 1) * len(train_dataloader))
  avg_next_loss = sum(losses_next) / ((epoch + 1) * len(train_dataloader))

  print(f"Total: {avg_total_loss}  CE: {avg_ce_loss} X: {avg_x_loss}  Y: {avg_y_loss} Next: {avg_next_loss}")

  0%|          | 0/56 [00:00<?, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/loss.py:535: UserWarning: Using a target size (torch.Size([1, 1])) that is different to the input size (torch.Size([1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


Total: 21.834269952774047  CE: 4.830816161632538 X: 6.717249272763729  Y: 10.025165058672428 Next: 0.26103938519954684


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 14.759497237205505  CE: 4.0513842642307285 X: 4.013342133184596  Y: 6.537543189525604 Next: 0.15722757996991277


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 11.757412385940551  CE: 3.7199317733446757 X: 2.907756290233495  Y: 5.009610640940567 Next: 0.12011369839310646


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 9.964530777931213  CE: 3.4455606073141096 X: 2.353687104039909  Y: 4.071331520797685 Next: 0.0939515608130023


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 8.750930762290954  CE: 3.258438808917999 X: 2.1208753795746453  Y: 3.2925756444083527 Next: 0.0790409460105002


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 7.921212844053904  CE: 3.181417359908422 X: 1.8443607495330676  Y: 2.827062610311744 Next: 0.06837213211692869


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 7.184974299158369  CE: 3.0495605519839697 X: 1.6437561179801767  Y: 2.430817065027908 Next: 0.06084056468680501


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 6.577874295413494  CE: 2.9257398545742035 X: 1.4583399881040804  Y: 2.1388629796038003 Next: 0.054931471834424886


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 6.088478685749902  CE: 2.8123617039786444 X: 1.3175973868905808  Y: 1.908353499425478 Next: 0.050166095239627694


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 5.671404577493668  CE: 2.707869511842728 X: 1.194184615645354  Y: 1.7233215586970618 Next: 0.04602889172267169


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 5.333473350784995  CE: 2.632359201257879 X: 1.0903997268947105  Y: 1.568183932002946 Next: 0.04253049088980664


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 5.0631210307280226  CE: 2.5771366039911907 X: 1.0060004276763115  Y: 1.4397090061093574 Next: 0.04027500038112824


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 5.080611286713527  CE: 2.690526101222405 X: 0.9515980683281668  Y: 1.3956232815759835 Next: 0.04286384398046021


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 5.011056737388883  CE: 2.7499920989785878 X: 0.8955827862982655  Y: 1.3248985240966118 Next: 0.04058333525567182


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 4.9282094407081605  CE: 2.7644304203987122 X: 0.8421024179359665  Y: 1.2831949316398337 Next: 0.03848168038142224


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 4.80076623186469  CE: 2.76469197794795 X: 0.7901244504420901  Y: 1.2089675380937366 Next: 0.03698227480927017


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 4.6745373340214  CE: 2.7558826649890227 X: 0.7440110975725795  Y: 1.1391112384512514 Next: 0.03553234290824655


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 4.557093646128973  CE: 2.743405231502321 X: 0.7033300794317459  Y: 1.0762608746976488 Next: 0.034097469383333294


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 4.450019345158025  CE: 2.7302702495926305 X: 0.6669076405550617  Y: 1.0197089248569562 Next: 0.03313254042724638


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 4.346459481120109  CE: 2.7119146150350573 X: 0.6337012073591086  Y: 0.9689238621772779 Next: 0.03191980604548007


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 4.243006697722843  CE: 2.6856581619807653 X: 0.6035999520726061  Y: 0.9228433043064602 Next: 0.030905289566587835


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 4.132010355862704  CE: 2.645052800395272 X: 0.5761915229998149  Y: 0.8809725027592841 Next: 0.0297935404476117


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 4.021830744847008  CE: 2.5984825020251066 X: 0.5515617328464111  Y: 0.8429361382089928 Next: 0.028850381703966338


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 3.920552993317445  CE: 2.5558893998463947 X: 0.5287233199675635  Y: 0.8078596426008765 Next: 0.02808064010265904


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 3.8183905825614928  CE: 2.5076621980667113 X: 0.5075943814720085  Y: 0.7755877740611706 Next: 0.027546237921342254


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 3.714517478988721  CE: 2.4529292521568444 X: 0.4881057189206191  Y: 0.7457721892912229 Next: 0.027710327078015184


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 3.6092735169110477  CE: 2.3938235104084016 X: 0.4700392454180926  Y: 0.7182535955472559 Next: 0.027157173083267278


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 3.5204038866928644  CE: 2.3458819378699576 X: 0.4546297132790753  Y: 0.6933823044500532 Next: 0.026509937873509314


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 3.4545046300723636  CE: 2.3196268466012233 X: 0.43902652926100816  Y: 0.6698341751844323 Next: 0.026017084280992378


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 3.391781447728475  CE: 2.2942840228478114 X: 0.4244295838189144  Y: 0.6475520370084248 Next: 0.025515809144514304


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 3.318691389791427  CE: 2.256259345239209 X: 0.41075817338438453  Y: 0.6267707049700882 Next: 0.02490317084781465


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 3.243041435070336  CE: 2.2133583940565584 X: 0.397969407463148  Y: 0.6073333428532566 Next: 0.02438029583208845


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 3.1673778125734042  CE: 2.167975360696966 X: 0.38652419139963234  Y: 0.5890210331666094 Next: 0.02385723163218548


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 3.093601045889013  CE: 2.1232569422791987 X: 0.3751794598940195  Y: 0.5717640312603459 Next: 0.023400616371209788


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 3.0247813623292106  CE: 2.081059696504048 X: 0.3645733353904557  Y: 0.5558060942096782 Next: 0.023342240300428654


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 2.95596561084191  CE: 2.0379686884582044 X: 0.354452383842964  Y: 0.5404774080526054 Next: 0.023067134242996366


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 2.894047388595504  CE: 2.000497971757038 X: 0.34494464740305975  Y: 0.5259346715403413 Next: 0.022670102205656066


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 2.8390225594765264  CE: 1.9679395805064002 X: 0.33635617095568643  Y: 0.5125233031591816 Next: 0.02220350889256224


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 2.7828748562397103  CE: 1.9328187347986758 X: 0.3285265977313731  Y: 0.49953624202251606 Next: 0.021993285701132546


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 2.7255284751951696  CE: 1.896229565292597 X: 0.32034572122274296  Y: 0.48728018968175363 Next: 0.021673002876341343


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 2.6732014097818513  CE: 1.8617453525706036 X: 0.31352827861109966  Y: 0.4765197981195302 Next: 0.021407984369207263


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 2.6827490786711374  CE: 1.8493726782145954 X: 0.32700087015365153  Y: 0.48437800460304403 Next: 0.021997528786527082


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 3.034793107176936  CE: 1.8411634215781856 X: 0.46217288589280164  Y: 0.7089672588473407 Next: 0.02248952900936697


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 3.05655095604333  CE: 1.8337199065495622 X: 0.46825397745533365  Y: 0.7314206437441441 Next: 0.023156418216901578


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 3.0706361328230964  CE: 1.8247908586263657 X: 0.47411519824410003  Y: 0.7487397646759951 Next: 0.022990301196049483


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 3.0592602725910103  CE: 1.8089495843519334 X: 0.4697687751732743  Y: 0.7578645081667578 Next: 0.022677394145917473


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 3.020675814151764  CE: 1.7942179464913428 X: 0.46046282697066987  Y: 0.7433004255759078 Next: 0.022694604204313712


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 2.9790027536451817  CE: 1.77559813366582 X: 0.450977406806692  Y: 0.729870939700855 Next: 0.02255626300126702


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 2.9340045141930484  CE: 1.7536264519302212 X: 0.4418121172972515  Y: 0.7162248456259832 Next: 0.022341089265668117


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 2.8896621524095534  CE: 1.7314527027606965 X: 0.4329804566582246  Y: 0.7030518482133215 Next: 0.022177134748082607


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 2.8471898975325565  CE: 1.7113636271626342 X: 0.42452100975094875  Y: 0.6893283575965289 Next: 0.021976893349075873


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 2.805444334447384  CE: 1.6912879250370538 X: 0.41635992943593736  Y: 0.676101208426736 Next: 0.021695262052638168


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 2.764633804222323  CE: 1.6713338189529923 X: 0.4085136037091202  Y: 0.663363151821992 Next: 0.02142322035682089


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 2.724642863428151  CE: 1.6513011441186622 X: 0.4009520769446932  Y: 0.6510888954301572 Next: 0.02130073785212719


0it [00:00, ?it/s]

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


Total: 2.684482734745199  CE: 1.6304808353294025 X: 0.39367076225907033  Y: 0.6392996486325346 Next: 0.021031479576433247


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


0it [00:00, ?it/s]

Total: 2.644657864049077  CE: 1.6092118011521441 X: 0.3866464485047046  Y: 0.6279946559650149 Next: 0.020804949650274854


In [167]:
# for epoch in tqdm(range(50, 56)):
#   gc.collect()
#   for i, batch in tqdm(enumerate(train_dataloader)):
#       mapped_img_embeddings = vit_to_llm(batch["current_img_emb"].reshape(batch["current_img_emb"].shape[0], 1, -1).to("cuda"))
#       ins_prefix_embeddings = model.base_model.model.model.embed_tokens(batch["ins_prefix_tokens"]["input_ids"].squeeze(1))
#       ins_suffix_embeddings = model.base_model.model.model.embed_tokens(batch["ins_suffix_tokens"]["input_ids"].squeeze(1))
#       embeddings = torch.cat([ins_prefix_embeddings, mapped_img_embeddings, ins_suffix_embeddings], dim=1)

#       out = model(inputs_embeds=embeddings.half(), labels=batch["ins_placeholder_tokens"]["input_ids"], output_hidden_states=True)

#       last_hidden_state = out.hidden_states[-1][:, -1, :].type(torch.float32)
#       x_out = X_head(last_hidden_state)
#       y_out = Y_head(last_hidden_state)
#       next_img_out = next_img_head(last_hidden_state)

#       ce_loss = out.loss
#       x_loss = mse_loss(batch["action_x"].to("cuda"), x_out)
#       y_loss = mse_loss(batch["action_y"].to("cuda"), y_out)
#       next_img_loss = mse_loss(batch["next_img_emb"].to("cuda"), next_img_out)

#       loss = ce_loss + x_loss + y_loss + next_img_loss

#       # loss.backward(retain_graph=True)

#       # if step % 100 == 0:
#       #     G_loss = torch.autograd.grad(loss, W.parameters(), retain_graph=True, create_graph=True)
#       #     G_loss_norm = torch.norm(G_loss[0], 2) # G_loss[0] = weights G_loss[1] = bias
#       #     G_triplet = torch.autograd.grad(loss_triplet, W.parameters(), retain_graph=True, create_graph=True)
#       #     G_triplet_norm = torch.norm(G_triplet[0], 2)
#       #     G_ce = torch.autograd.grad(loss_ce, W.parameters(), retain_graph=True, create_graph=True)
#       #     G_ce_norm = torch.norm(G_ce[0], 2)

#       #     grads_total.append(G_loss_norm.item())
#       #     grads_triplets.append(G_triplet_norm.item())
#       #     grads_ce.append(G_ce_norm.item())

#       loss.backward()
#       optimizer.step()
#       optimizer.zero_grad()

#       # if step % 100 == 0:
#       losses_total.append(loss.item())
#       losses_ce.append(ce_loss.item())
#       losses_x.append(x_loss.item())
#       losses_y.append(y_loss.item())
#       losses_next.append(next_img_loss.item())

#   avg_total_loss = sum(losses_total) / ((epoch + 1) * len(train_dataloader))
#   avg_ce_loss = sum(losses_ce) / ((epoch + 1) * len(train_dataloader))
#   avg_x_loss = sum(losses_x) / ((epoch + 1) * len(train_dataloader))
#   avg_y_loss = sum(losses_y) / ((epoch + 1) * len(train_dataloader))
#   avg_next_loss = sum(losses_next) / ((epoch + 1) * len(train_dataloader))

#   print(f"Total: {avg_total_loss}  CE: {avg_ce_loss} X: {avg_x_loss}  Y: {avg_y_loss} Next: {avg_next_loss}")

In [168]:
test_ds = LlameDataset(
    img_embeddings_t[11:20],
    next_img_embeddings_t[11:20],
    actions_t[11:20],
    instructions[11:20],
    tokenizer
)

In [169]:
test_dl = DataLoader(
    test_ds,
    batch_size=1,
    num_workers=1
)

In [170]:
_, _d = next(enumerate(test_dl))

Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


In [171]:
_img_emb = vit_to_llm(_d["current_img_emb"].reshape(_d["current_img_emb"].shape[0], 1, -1).to("cuda"))
p_emb = model.base_model.model.model.embed_tokens(_d["ins_prefix_tokens"]["input_ids"].squeeze(1))
s_emb = model.base_model.model.model.embed_tokens(_d["ins_suffix_tokens"]["input_ids"].squeeze(1))
_merged_emb = torch.cat([p_emb, _img_emb, s_emb], dim=1)
print(_merged_emb.shape)

torch.Size([1, 34, 4096])


In [172]:
gc.collect()

214

In [173]:
_gen = model.generate(
    inputs_embeds=_merged_emb,
    return_dict_in_generate=True,
    output_scores=True,
    output_hidden_states=True,
    max_new_tokens=50
)

In [174]:
_gen

SampleDecoderOnlyOutput(sequences=tensor([[    1,   278,   278,   278,   278, 29871,   278,   278,   278,   278,
         29871,   278, 29871,   278, 11137,   278, 32001, 11137, 29871, 32002,
         29871, 29871, 29871, 32001, 29871, 29871, 29871, 32001,   278, 32003,
           411,   278,   278, 29871,   278, 11137, 32001, 12841, 32001, 29871,
           278, 29871, 29871,  2654, 32001,   411, 12841, 29871, 29871, 29871,
           278]], device='cuda:0'), scores=(tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0'), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0'), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0'), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0'), tensor([[   -inf,    -inf,    -inf,  ...,    -inf, 24.0454,    -inf]],
       device='cuda:0'), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0'), tensor([[-inf, -inf, -inf,  ..., -inf, -inf, -inf]], device='cuda:0'), tenso

In [175]:
hs = _gen.hidden_states
seq = _gen.sequences

In [176]:
seq

tensor([[    1,   278,   278,   278,   278, 29871,   278,   278,   278,   278,
         29871,   278, 29871,   278, 11137,   278, 32001, 11137, 29871, 32002,
         29871, 29871, 29871, 32001, 29871, 29871, 29871, 32001,   278, 32003,
           411,   278,   278, 29871,   278, 11137, 32001, 12841, 32001, 29871,
           278, 29871, 29871,  2654, 32001,   411, 12841, 29871, 29871, 29871,
           278]], device='cuda:0')

In [177]:
tokenizer.batch_decode(seq, skip_special_tokens=True)

['the the the the  the the the the  the  the pent the pent        the with the the  the pentagon  the   red withagon    the']

In [178]:
_d["action_x"]

tensor([0.0024])

In [179]:
_d["action_y"]

tensor([-0.0175])

In [180]:
_next_img_e = _d["next_img_emb"].to("cuda")

In [181]:
for i in range(10):
  last_hidden_state = hs[i][-1][:, -1, :]
  _out_x = X_head(last_hidden_state)
  _out_y = Y_head(last_hidden_state)
  _out_next = next_img_head(last_hidden_state)
  print(_out_x)
  print(_out_y)
  print(nn.functional.cosine_similarity(_out_next, _next_img_e))
  print("-" * 10)


tensor([[0.0728]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.1484]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0.9137], device='cuda:0', grad_fn=<SumBackward1>)
----------
tensor([[0.0041]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[-0.0087]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0.9155], device='cuda:0', grad_fn=<SumBackward1>)
----------
tensor([[-2.3133e-05]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[0.0096]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0.8902], device='cuda:0', grad_fn=<SumBackward1>)
----------
tensor([[0.0128]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[0.0422]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0.9179], device='cuda:0', grad_fn=<SumBackward1>)
----------
tensor([[0.0597]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([[0.0874]], device='cuda:0', grad_fn=<AddmmBackward0>)
tensor([0.9207], device='cuda:0', grad_fn=<SumBackward1>)
----------
tensor([[0.5069]], device='c